# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Christof Seiler
tagline:          'Research'
description:      'Postdoctoral Fellow<br>Department of Statistics<br>Stanford University'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Christof Seiler'
  url:            https://cseiler.web.stanford.edu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ChristofSeiler/ChristofSeiler.github.io
