# Dependencies
#markdown:         kramdown
#highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Christof Seiler
tagline:          ''
description:      'Research Scientist<br>Stanford University'
url:              http://christofseiler.github.io
baseurl:          /

author:
  name:           'Christof Seiler'
  url:            http://christofseiler.github.io

gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ChristofSeiler/ChristofSeiler.github.io
